/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 model.glb --transform
Author: Yannick Deharo (https://sketchfab.com/YannickDeharo)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/20-liquor-bottles-4729b1cfa5b74db68924190242f8ac76
Title: 20 Liquor bottles
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cointreau_Atlas_0.geometry} material={materials.Atlas} position={[29.026, 0, 39.951]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Molinari_Sambuka_Sprite_Sprites_0.geometry} material={materials.Sprites} position={[29.019, 0.074, -39.941]} rotation={[-Math.PI / 2, 0, 2.513]} />
    </group>
  )
}

useGLTF.preload('/model-transformed.glb')
