/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 scene.gltf --transform
Author: NKaap (https://sketchfab.com/nkaap)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/prime-bottle-tropical-punch-gameready-free-7f02d5806ea34cf39d9a4f9cd0d16979
Title: Prime Bottle | Tropical Punch | Gameready | Free
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Material_001} rotation={[0, Math.PI / 2, 0]} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
